[Writable]
LogLevel = 'INFO'

[Service]
Host = "device-gps"
Port = 49990
ConnectRetries = 20
Labels = []
OpenMsg = "GPS device started"
ReadMaxLimit = 256
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
Type = "consul"
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Logging]
EnableRemote = true
File = "/edgex/logs/device-gps.log"

# Pre-define Devices
[[DeviceList]]
  Name = "device-gps01"
  Profile = "device-gps"
  Description = "Example of GPS Device"
  Labels = [ "IoT" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "GPS01"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "1s"
    OnChange = false
    Resource = "GPS"
